export const modules = [
    "Requisitions",
    "Contract",
    "Sourcing",
    "Auction",
    "Non-Catalog Requisitions",
    "Dispatch Notifications",
    "Sourcing Pending Items",
    "Purchase Orders",
    "Central Procurement",
    "PO Amendment",
    "DMS Documents",
    "Logistic SPOC",
    "GRN",
    "Service Note",
    "Service Entry Sheet",
    "Invoices",
    "GRN Acknowledge",
    "GRN/SES Reports",
    "Catalog",
    "Suppliers",
    "Return Delivery",
    "Admin",
    "Reports",
    "Finance Report"
  ]
  